- name: Install PIP, notepad++ from chocolatey
  hosts: win-test
  tasks:
    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: latest

    - name: Install Python3
      win_chocolatey:
        name: python3
        state: latest

    - name: Install Rsync
      win_chocolatey:
        name: rsync
        state: latest

